---
- hosts: all
  sudo: true
  # What tasks do we need to run?
  vars:
    - domain: demo.dev
  tasks:
  - name: make sure we can connect
    action: ping
  # Install nginx, php, mysql, git
  - name: apt-get update
    apt: update_cache=yes
  - name: Install PHP
    apt: pkg={{item}} state=installed
    with_items:
      - php5-cli
      - php5-dev
      - php5-mysql
      - php5-json
  - name: install mysql-server
    apt: pkg=mysql-server state=installed
  - name: install git
    apt: pkg=git state=installed
  - name: install vim
    apt: pkg=vim state=installed
  - name: install nginx
    apt: pkg=nginx state=installed

  # Modify nginx configs
  - name: modify nginx conf
    template: src=templates/nginx/nginx.conf dest=/etc/nginx/nginx.conf owner=vagrant group=vagrant
    notify:
      - restart nginx
  - name: create wp-blog vhost
    template: src=templates/nginx/wp-blog.conf dest=/etc/nginx/sites-available/wp-blog.conf owner=vagrant group=vagrant
    notify:
      - restart nginx

  # Notification handlers
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted